version: '3.8'

services:
  web:
    build: ./
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://user:password@db/mydatabase

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - db_data:/var/lib/mysql

  alembic:
    build:
      context: .
      dockerfile: Dockerfile
    command: alembic revision --autogenerate -m 'Initial migration'
    environment:
      DATABASE_URL : "mysql+mysqldb://user:password@db/mydatabase"
    volumes:
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
      - ./models.py:/app/models.py

volumes:
  db_data:

