"""Migration

Revision ID: 74b10ed8e06c
Revises: 7b91c9f3369d
Create Date: 2024-02-12 02:20:15.431493

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "74b10ed8e06c"
down_revision: Union[str, None] = "7b91c9f3369d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("email", table_name="users")
    op.drop_column("users", "email")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("email", mysql.VARCHAR(length=100), nullable=False)
    )
    op.create_index("email", "users", ["email"], unique=True)
    # ### end Alembic commands ###
